version: '3.9'

services:
  # MongoDb Service
  mongo_db: 
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    # volumes:
    #   - mongo_db:/data/db
    # networks:
    #   - app-network

  api-server:
    build: ./server/
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
    # networks:
    #   - app-network

  # client:
  #   build: ./client/
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - api-server
  #   networks:
  #     - app-network

# volumes:
#   mongo_db:

# networks:
#   app-network:
#     driver: bridge